version: "3.9"

services:
  database:
    container_name: microservice_mysql_container
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: urun
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_database:/var/lib/mysql
    networks:
      - my-network

  rabbitmq:
    container_name: microservice_rabbitmq_container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  elasticsearch:
    container_name: microservice_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      - my-network

  kibana:
    container_name: microservice_kibana
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my-network


  grafana:
    container_name: microservice_grafana
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    networks:
      - my-network

  zipkin:
    container_name: microservice_zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - my-network

volumes:
  mysql_database:
  esdata:

networks:
  my-network:
